include: package:very_good_analysis/analysis_options.yaml

formatter:
  trailing_commas: automate

analyzer:
  errors:
    curly_braces_in_flow_control_structures: ignore
    public_member_api_docs: ignore
