// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class MapKitHostError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "MapKitHostError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? MapKitHostError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> MapKitHostError {
  return MapKitHostError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum messagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        if let rhsValue = rhsDictionary[lhsKey] {
          if !deepEquals(lhsValue, rhsValue) {
            return false
          }
        } else {
          return false
        }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum PlatformMapKind: Int, CaseIterable {
  case standard = 0
  case hybrid = 1
  case imagery = 2
}

/// Label and feature emphasis on the standard map
/// (`MKStandardMapConfiguration.EmphasisStyle`).
///
/// `standard` maps to Apple's `.default` — `default` is a Dart reserved word.
/// See: https://developer.apple.com/documentation/mapkit/mkstandardmapconfiguration/emphasisstyle
enum PlatformMapEmphasisStyle: Int, CaseIterable {
  case standard = 0
  case muted = 1
}

/// Flat versus realistic 3-D terrain (`MKMapConfiguration.ElevationStyle`).
/// See: https://developer.apple.com/documentation/mapkit/mkmapconfiguration/elevationstyle
enum PlatformMapElevationStyle: Int, CaseIterable {
  case flat = 0
  case realistic = 1
}

/// How the map camera follows the user's location (`MKUserTrackingMode`).
/// See: https://developer.apple.com/documentation/mapkit/mkusertrackingmode
enum PlatformUserTrackingMode: Int, CaseIterable {
  case none = 0
  case follow = 1
  case followWithHeading = 2
}

/// Stroke end-cap style for an `MKPolyline` (`CGLineCap`).
/// See: https://developer.apple.com/documentation/coregraphics/cglinecap
enum PlatformLineCap: Int, CaseIterable {
  case butt = 0
  case round = 1
  case square = 2
}

/// Stroke join style between `MKPolyline` segments (`CGLineJoin`).
/// See: https://developer.apple.com/documentation/coregraphics/cglinejoin
enum PlatformLineJoin: Int, CaseIterable {
  case miter = 0
  case round = 1
  case bevel = 2
}

enum PlatformPOIMode: Int, CaseIterable {
  case none = 0
  case all = 1
  case including = 2
  case excluding = 3
}

/// Vertical placement of an overlay relative to the base map's own labels and
/// roads (`MKOverlayLevel`).
/// See: https://developer.apple.com/documentation/mapkit/mkoverlaylevel
enum PlatformOverlayLevel: Int, CaseIterable {
  /// Drawn above roads but below map labels (POIs, place names). Default.
  case aboveRoads = 0
  /// Drawn above everything, including labels.
  case aboveLabels = 1
}

/// Mirrors `MKPointOfInterestCategory`.
/// See: https://developer.apple.com/documentation/mapkit/mkpointofinterestcategory
enum PlatformPointOfInterestCategory: Int, CaseIterable {
  case airport = 0
  case amusementPark = 1
  case aquarium = 2
  case atm = 3
  case bakery = 4
  case bank = 5
  case beach = 6
  case brewery = 7
  case cafe = 8
  case campground = 9
  case carRental = 10
  case evCharger = 11
  case fireStation = 12
  case fitnessCenter = 13
  case foodMarket = 14
  case gasStation = 15
  case hospital = 16
  case hotel = 17
  case laundry = 18
  case library = 19
  case marina = 20
  case movieTheater = 21
  case museum = 22
  case nationalPark = 23
  case nightlife = 24
  case park = 25
  case parking = 26
  case pharmacy = 27
  case police = 28
  case postOffice = 29
  case publicTransport = 30
  case restaurant = 31
  case restroom = 32
  case school = 33
  case stadium = 34
  case store = 35
  case theater = 36
  case university = 37
  case winery = 38
  case zoo = 39
}

/// Map features the user can select (`MKMapFeatureOptions`).
/// See: https://developer.apple.com/documentation/mapkit/mkmapfeatureoptions
enum PlatformMapFeatureOptions: Int, CaseIterable {
  case pointsOfInterest = 0
  case territories = 1
  case physicalFeatures = 2
}

enum PlatformAnnotationIconType: Int, CaseIterable {
  case marker = 0
  case image = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCoordinate: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCoordinate? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return PlatformCoordinate(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: PlatformCoordinate, rhs: PlatformCoordinate) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && messagesPigeonInternal.deepEquals(lhs.longitude, rhs.longitude)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformCoordinate")
    messagesPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: longitude, hasher: &hasher)
  }

  public var description: String {
    return "PlatformCoordinate(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCoordinateSpan: Hashable, CustomStringConvertible {
  var latitudeDelta: Double
  var longitudeDelta: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCoordinateSpan? {
    let latitudeDelta = pigeonVar_list[0] as! Double
    let longitudeDelta = pigeonVar_list[1] as! Double

    return PlatformCoordinateSpan(
      latitudeDelta: latitudeDelta,
      longitudeDelta: longitudeDelta
    )
  }
  func toList() -> [Any?] {
    return [
      latitudeDelta,
      longitudeDelta,
    ]
  }
  static func == (lhs: PlatformCoordinateSpan, rhs: PlatformCoordinateSpan) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.latitudeDelta, rhs.latitudeDelta) && messagesPigeonInternal.deepEquals(lhs.longitudeDelta, rhs.longitudeDelta)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformCoordinateSpan")
    messagesPigeonInternal.deepHash(value: latitudeDelta, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: longitudeDelta, hasher: &hasher)
  }

  public var description: String {
    return "PlatformCoordinateSpan(latitudeDelta: \(String(describing: latitudeDelta)), longitudeDelta: \(String(describing: longitudeDelta)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCoordinateRegion: Hashable, CustomStringConvertible {
  var center: PlatformCoordinate
  var span: PlatformCoordinateSpan


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCoordinateRegion? {
    let center = pigeonVar_list[0] as! PlatformCoordinate
    let span = pigeonVar_list[1] as! PlatformCoordinateSpan

    return PlatformCoordinateRegion(
      center: center,
      span: span
    )
  }
  func toList() -> [Any?] {
    return [
      center,
      span,
    ]
  }
  static func == (lhs: PlatformCoordinateRegion, rhs: PlatformCoordinateRegion) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.center, rhs.center) && messagesPigeonInternal.deepEquals(lhs.span, rhs.span)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformCoordinateRegion")
    messagesPigeonInternal.deepHash(value: center, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: span, hasher: &hasher)
  }

  public var description: String {
    return "PlatformCoordinateRegion(center: \(String(describing: center)), span: \(String(describing: span)))"
  }
}

/// Mirrors `MKMapCamera`: [distance] is `centerCoordinateDistance` in meters.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMapCamera: Hashable, CustomStringConvertible {
  var centerCoordinate: PlatformCoordinate
  var distance: Double
  var heading: Double
  var pitch: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMapCamera? {
    let centerCoordinate = pigeonVar_list[0] as! PlatformCoordinate
    let distance = pigeonVar_list[1] as! Double
    let heading = pigeonVar_list[2] as! Double
    let pitch = pigeonVar_list[3] as! Double

    return PlatformMapCamera(
      centerCoordinate: centerCoordinate,
      distance: distance,
      heading: heading,
      pitch: pitch
    )
  }
  func toList() -> [Any?] {
    return [
      centerCoordinate,
      distance,
      heading,
      pitch,
    ]
  }
  static func == (lhs: PlatformMapCamera, rhs: PlatformMapCamera) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.centerCoordinate, rhs.centerCoordinate) && messagesPigeonInternal.deepEquals(lhs.distance, rhs.distance) && messagesPigeonInternal.deepEquals(lhs.heading, rhs.heading) && messagesPigeonInternal.deepEquals(lhs.pitch, rhs.pitch)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformMapCamera")
    messagesPigeonInternal.deepHash(value: centerCoordinate, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: distance, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: heading, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: pitch, hasher: &hasher)
  }

  public var description: String {
    return "PlatformMapCamera(centerCoordinate: \(String(describing: centerCoordinate)), distance: \(String(describing: distance)), heading: \(String(describing: heading)), pitch: \(String(describing: pitch)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPoint: Hashable, CustomStringConvertible {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPoint? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return PlatformPoint(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
  static func == (lhs: PlatformPoint, rhs: PlatformPoint) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.x, rhs.x) && messagesPigeonInternal.deepEquals(lhs.y, rhs.y)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformPoint")
    messagesPigeonInternal.deepHash(value: x, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: y, hasher: &hasher)
  }

  public var description: String {
    return "PlatformPoint(x: \(String(describing: x)), y: \(String(describing: y)))"
  }
}

/// Discriminated union of the `MKAnnotationIcon` variants. Only the fields
/// relevant to [type] are non-null.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAnnotationIcon: Hashable, CustomStringConvertible {
  var type: PlatformAnnotationIconType
  /// `MKMarkerAnnotationView.markerTintColor` (ARGB) for the `marker` variant.
  var markerTintArgb: Int64? = nil
  /// `MKMarkerAnnotationView.glyphText` for the `marker` variant.
  var glyphText: String? = nil
  /// SF Symbol name for `MKMarkerAnnotationView.glyphImage`.
  var glyphSystemImage: String? = nil
  /// `MKMarkerAnnotationView.glyphTintColor` (ARGB).
  var glyphTintArgb: Int64? = nil
  /// Raw PNG bytes for the `image` variant (`MKAnnotationView.image`).
  var imageBytes: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAnnotationIcon? {
    let type = pigeonVar_list[0] as! PlatformAnnotationIconType
    let markerTintArgb: Int64? = nilOrValue(pigeonVar_list[1])
    let glyphText: String? = nilOrValue(pigeonVar_list[2])
    let glyphSystemImage: String? = nilOrValue(pigeonVar_list[3])
    let glyphTintArgb: Int64? = nilOrValue(pigeonVar_list[4])
    let imageBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[5])

    return PlatformAnnotationIcon(
      type: type,
      markerTintArgb: markerTintArgb,
      glyphText: glyphText,
      glyphSystemImage: glyphSystemImage,
      glyphTintArgb: glyphTintArgb,
      imageBytes: imageBytes
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      markerTintArgb,
      glyphText,
      glyphSystemImage,
      glyphTintArgb,
      imageBytes,
    ]
  }
  static func == (lhs: PlatformAnnotationIcon, rhs: PlatformAnnotationIcon) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.type, rhs.type) && messagesPigeonInternal.deepEquals(lhs.markerTintArgb, rhs.markerTintArgb) && messagesPigeonInternal.deepEquals(lhs.glyphText, rhs.glyphText) && messagesPigeonInternal.deepEquals(lhs.glyphSystemImage, rhs.glyphSystemImage) && messagesPigeonInternal.deepEquals(lhs.glyphTintArgb, rhs.glyphTintArgb) && messagesPigeonInternal.deepEquals(lhs.imageBytes, rhs.imageBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformAnnotationIcon")
    messagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: markerTintArgb, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: glyphText, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: glyphSystemImage, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: glyphTintArgb, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: imageBytes, hasher: &hasher)
  }

  public var description: String {
    return "PlatformAnnotationIcon(type: \(String(describing: type)), markerTintArgb: \(String(describing: markerTintArgb)), glyphText: \(String(describing: glyphText)), glyphSystemImage: \(String(describing: glyphSystemImage)), glyphTintArgb: \(String(describing: glyphTintArgb)), imageBytes: \(String(describing: imageBytes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAnnotation: Hashable, CustomStringConvertible {
  var id: String
  var coordinate: PlatformCoordinate
  var icon: PlatformAnnotationIcon
  var title: String? = nil
  var subtitle: String? = nil
  var calloutConsumesTapEvents: Bool
  var alpha: Double
  var anchorPointX: Double
  var anchorPointY: Double
  var isDraggable: Bool
  var isHidden: Bool
  var zPriority: Double
  var clusteringIdentifier: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAnnotation? {
    let id = pigeonVar_list[0] as! String
    let coordinate = pigeonVar_list[1] as! PlatformCoordinate
    let icon = pigeonVar_list[2] as! PlatformAnnotationIcon
    let title: String? = nilOrValue(pigeonVar_list[3])
    let subtitle: String? = nilOrValue(pigeonVar_list[4])
    let calloutConsumesTapEvents = pigeonVar_list[5] as! Bool
    let alpha = pigeonVar_list[6] as! Double
    let anchorPointX = pigeonVar_list[7] as! Double
    let anchorPointY = pigeonVar_list[8] as! Double
    let isDraggable = pigeonVar_list[9] as! Bool
    let isHidden = pigeonVar_list[10] as! Bool
    let zPriority = pigeonVar_list[11] as! Double
    let clusteringIdentifier: String? = nilOrValue(pigeonVar_list[12])

    return PlatformAnnotation(
      id: id,
      coordinate: coordinate,
      icon: icon,
      title: title,
      subtitle: subtitle,
      calloutConsumesTapEvents: calloutConsumesTapEvents,
      alpha: alpha,
      anchorPointX: anchorPointX,
      anchorPointY: anchorPointY,
      isDraggable: isDraggable,
      isHidden: isHidden,
      zPriority: zPriority,
      clusteringIdentifier: clusteringIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      coordinate,
      icon,
      title,
      subtitle,
      calloutConsumesTapEvents,
      alpha,
      anchorPointX,
      anchorPointY,
      isDraggable,
      isHidden,
      zPriority,
      clusteringIdentifier,
    ]
  }
  static func == (lhs: PlatformAnnotation, rhs: PlatformAnnotation) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.coordinate, rhs.coordinate) && messagesPigeonInternal.deepEquals(lhs.icon, rhs.icon) && messagesPigeonInternal.deepEquals(lhs.title, rhs.title) && messagesPigeonInternal.deepEquals(lhs.subtitle, rhs.subtitle) && messagesPigeonInternal.deepEquals(lhs.calloutConsumesTapEvents, rhs.calloutConsumesTapEvents) && messagesPigeonInternal.deepEquals(lhs.alpha, rhs.alpha) && messagesPigeonInternal.deepEquals(lhs.anchorPointX, rhs.anchorPointX) && messagesPigeonInternal.deepEquals(lhs.anchorPointY, rhs.anchorPointY) && messagesPigeonInternal.deepEquals(lhs.isDraggable, rhs.isDraggable) && messagesPigeonInternal.deepEquals(lhs.isHidden, rhs.isHidden) && messagesPigeonInternal.deepEquals(lhs.zPriority, rhs.zPriority) && messagesPigeonInternal.deepEquals(lhs.clusteringIdentifier, rhs.clusteringIdentifier)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformAnnotation")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: coordinate, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: icon, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: subtitle, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: calloutConsumesTapEvents, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: alpha, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: anchorPointX, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: anchorPointY, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isDraggable, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isHidden, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: zPriority, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: clusteringIdentifier, hasher: &hasher)
  }

  public var description: String {
    return "PlatformAnnotation(id: \(String(describing: id)), coordinate: \(String(describing: coordinate)), icon: \(String(describing: icon)), title: \(String(describing: title)), subtitle: \(String(describing: subtitle)), calloutConsumesTapEvents: \(String(describing: calloutConsumesTapEvents)), alpha: \(String(describing: alpha)), anchorPointX: \(String(describing: anchorPointX)), anchorPointY: \(String(describing: anchorPointY)), isDraggable: \(String(describing: isDraggable)), isHidden: \(String(describing: isHidden)), zPriority: \(String(describing: zPriority)), clusteringIdentifier: \(String(describing: clusteringIdentifier)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPolyline: Hashable, CustomStringConvertible {
  var id: String
  var coordinates: [PlatformCoordinate]
  var strokeColorArgb: Int64
  var lineWidth: Double
  var lineCap: PlatformLineCap
  var lineJoin: PlatformLineJoin
  var isHidden: Bool
  var consumeTapEvents: Bool
  var isGeodesic: Bool
  var level: PlatformOverlayLevel
  var zIndex: Int64
  /// Alternating dash/gap lengths in points (`lineDashPattern`).
  var lineDashPattern: [Double]? = nil
  /// When non-empty, renders with `MKGradientPolylineRenderer` spreading these
  /// ARGB colors evenly across the line.
  var gradientColorsArgb: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPolyline? {
    let id = pigeonVar_list[0] as! String
    let coordinates = pigeonVar_list[1] as! [PlatformCoordinate]
    let strokeColorArgb = pigeonVar_list[2] as! Int64
    let lineWidth = pigeonVar_list[3] as! Double
    let lineCap = pigeonVar_list[4] as! PlatformLineCap
    let lineJoin = pigeonVar_list[5] as! PlatformLineJoin
    let isHidden = pigeonVar_list[6] as! Bool
    let consumeTapEvents = pigeonVar_list[7] as! Bool
    let isGeodesic = pigeonVar_list[8] as! Bool
    let level = pigeonVar_list[9] as! PlatformOverlayLevel
    let zIndex = pigeonVar_list[10] as! Int64
    let lineDashPattern: [Double]? = nilOrValue(pigeonVar_list[11])
    let gradientColorsArgb: [Int64]? = nilOrValue(pigeonVar_list[12])

    return PlatformPolyline(
      id: id,
      coordinates: coordinates,
      strokeColorArgb: strokeColorArgb,
      lineWidth: lineWidth,
      lineCap: lineCap,
      lineJoin: lineJoin,
      isHidden: isHidden,
      consumeTapEvents: consumeTapEvents,
      isGeodesic: isGeodesic,
      level: level,
      zIndex: zIndex,
      lineDashPattern: lineDashPattern,
      gradientColorsArgb: gradientColorsArgb
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      coordinates,
      strokeColorArgb,
      lineWidth,
      lineCap,
      lineJoin,
      isHidden,
      consumeTapEvents,
      isGeodesic,
      level,
      zIndex,
      lineDashPattern,
      gradientColorsArgb,
    ]
  }
  static func == (lhs: PlatformPolyline, rhs: PlatformPolyline) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.coordinates, rhs.coordinates) && messagesPigeonInternal.deepEquals(lhs.strokeColorArgb, rhs.strokeColorArgb) && messagesPigeonInternal.deepEquals(lhs.lineWidth, rhs.lineWidth) && messagesPigeonInternal.deepEquals(lhs.lineCap, rhs.lineCap) && messagesPigeonInternal.deepEquals(lhs.lineJoin, rhs.lineJoin) && messagesPigeonInternal.deepEquals(lhs.isHidden, rhs.isHidden) && messagesPigeonInternal.deepEquals(lhs.consumeTapEvents, rhs.consumeTapEvents) && messagesPigeonInternal.deepEquals(lhs.isGeodesic, rhs.isGeodesic) && messagesPigeonInternal.deepEquals(lhs.level, rhs.level) && messagesPigeonInternal.deepEquals(lhs.zIndex, rhs.zIndex) && messagesPigeonInternal.deepEquals(lhs.lineDashPattern, rhs.lineDashPattern) && messagesPigeonInternal.deepEquals(lhs.gradientColorsArgb, rhs.gradientColorsArgb)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformPolyline")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: coordinates, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: strokeColorArgb, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: lineWidth, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: lineCap, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: lineJoin, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isHidden, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: consumeTapEvents, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isGeodesic, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: level, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: zIndex, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: lineDashPattern, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: gradientColorsArgb, hasher: &hasher)
  }

  public var description: String {
    return "PlatformPolyline(id: \(String(describing: id)), coordinates: \(String(describing: coordinates)), strokeColorArgb: \(String(describing: strokeColorArgb)), lineWidth: \(String(describing: lineWidth)), lineCap: \(String(describing: lineCap)), lineJoin: \(String(describing: lineJoin)), isHidden: \(String(describing: isHidden)), consumeTapEvents: \(String(describing: consumeTapEvents)), isGeodesic: \(String(describing: isGeodesic)), level: \(String(describing: level)), zIndex: \(String(describing: zIndex)), lineDashPattern: \(String(describing: lineDashPattern)), gradientColorsArgb: \(String(describing: gradientColorsArgb)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPolygon: Hashable, CustomStringConvertible {
  var id: String
  var coordinates: [PlatformCoordinate]
  var interiorPolygons: [[PlatformCoordinate]]
  var fillColorArgb: Int64
  var strokeColorArgb: Int64
  var lineWidth: Double
  var zIndex: Int64
  var isHidden: Bool
  var consumeTapEvents: Bool
  var level: PlatformOverlayLevel


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPolygon? {
    let id = pigeonVar_list[0] as! String
    let coordinates = pigeonVar_list[1] as! [PlatformCoordinate]
    let interiorPolygons = pigeonVar_list[2] as! [[PlatformCoordinate]]
    let fillColorArgb = pigeonVar_list[3] as! Int64
    let strokeColorArgb = pigeonVar_list[4] as! Int64
    let lineWidth = pigeonVar_list[5] as! Double
    let zIndex = pigeonVar_list[6] as! Int64
    let isHidden = pigeonVar_list[7] as! Bool
    let consumeTapEvents = pigeonVar_list[8] as! Bool
    let level = pigeonVar_list[9] as! PlatformOverlayLevel

    return PlatformPolygon(
      id: id,
      coordinates: coordinates,
      interiorPolygons: interiorPolygons,
      fillColorArgb: fillColorArgb,
      strokeColorArgb: strokeColorArgb,
      lineWidth: lineWidth,
      zIndex: zIndex,
      isHidden: isHidden,
      consumeTapEvents: consumeTapEvents,
      level: level
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      coordinates,
      interiorPolygons,
      fillColorArgb,
      strokeColorArgb,
      lineWidth,
      zIndex,
      isHidden,
      consumeTapEvents,
      level,
    ]
  }
  static func == (lhs: PlatformPolygon, rhs: PlatformPolygon) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.coordinates, rhs.coordinates) && messagesPigeonInternal.deepEquals(lhs.interiorPolygons, rhs.interiorPolygons) && messagesPigeonInternal.deepEquals(lhs.fillColorArgb, rhs.fillColorArgb) && messagesPigeonInternal.deepEquals(lhs.strokeColorArgb, rhs.strokeColorArgb) && messagesPigeonInternal.deepEquals(lhs.lineWidth, rhs.lineWidth) && messagesPigeonInternal.deepEquals(lhs.zIndex, rhs.zIndex) && messagesPigeonInternal.deepEquals(lhs.isHidden, rhs.isHidden) && messagesPigeonInternal.deepEquals(lhs.consumeTapEvents, rhs.consumeTapEvents) && messagesPigeonInternal.deepEquals(lhs.level, rhs.level)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformPolygon")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: coordinates, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: interiorPolygons, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: fillColorArgb, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: strokeColorArgb, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: lineWidth, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: zIndex, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isHidden, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: consumeTapEvents, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: level, hasher: &hasher)
  }

  public var description: String {
    return "PlatformPolygon(id: \(String(describing: id)), coordinates: \(String(describing: coordinates)), interiorPolygons: \(String(describing: interiorPolygons)), fillColorArgb: \(String(describing: fillColorArgb)), strokeColorArgb: \(String(describing: strokeColorArgb)), lineWidth: \(String(describing: lineWidth)), zIndex: \(String(describing: zIndex)), isHidden: \(String(describing: isHidden)), consumeTapEvents: \(String(describing: consumeTapEvents)), level: \(String(describing: level)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCircle: Hashable, CustomStringConvertible {
  var id: String
  var center: PlatformCoordinate
  var radius: Double
  var fillColorArgb: Int64
  var strokeColorArgb: Int64
  var lineWidth: Double
  var zIndex: Int64
  var isHidden: Bool
  var consumeTapEvents: Bool
  var level: PlatformOverlayLevel


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCircle? {
    let id = pigeonVar_list[0] as! String
    let center = pigeonVar_list[1] as! PlatformCoordinate
    let radius = pigeonVar_list[2] as! Double
    let fillColorArgb = pigeonVar_list[3] as! Int64
    let strokeColorArgb = pigeonVar_list[4] as! Int64
    let lineWidth = pigeonVar_list[5] as! Double
    let zIndex = pigeonVar_list[6] as! Int64
    let isHidden = pigeonVar_list[7] as! Bool
    let consumeTapEvents = pigeonVar_list[8] as! Bool
    let level = pigeonVar_list[9] as! PlatformOverlayLevel

    return PlatformCircle(
      id: id,
      center: center,
      radius: radius,
      fillColorArgb: fillColorArgb,
      strokeColorArgb: strokeColorArgb,
      lineWidth: lineWidth,
      zIndex: zIndex,
      isHidden: isHidden,
      consumeTapEvents: consumeTapEvents,
      level: level
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      center,
      radius,
      fillColorArgb,
      strokeColorArgb,
      lineWidth,
      zIndex,
      isHidden,
      consumeTapEvents,
      level,
    ]
  }
  static func == (lhs: PlatformCircle, rhs: PlatformCircle) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.center, rhs.center) && messagesPigeonInternal.deepEquals(lhs.radius, rhs.radius) && messagesPigeonInternal.deepEquals(lhs.fillColorArgb, rhs.fillColorArgb) && messagesPigeonInternal.deepEquals(lhs.strokeColorArgb, rhs.strokeColorArgb) && messagesPigeonInternal.deepEquals(lhs.lineWidth, rhs.lineWidth) && messagesPigeonInternal.deepEquals(lhs.zIndex, rhs.zIndex) && messagesPigeonInternal.deepEquals(lhs.isHidden, rhs.isHidden) && messagesPigeonInternal.deepEquals(lhs.consumeTapEvents, rhs.consumeTapEvents) && messagesPigeonInternal.deepEquals(lhs.level, rhs.level)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformCircle")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: center, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: radius, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: fillColorArgb, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: strokeColorArgb, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: lineWidth, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: zIndex, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isHidden, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: consumeTapEvents, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: level, hasher: &hasher)
  }

  public var description: String {
    return "PlatformCircle(id: \(String(describing: id)), center: \(String(describing: center)), radius: \(String(describing: radius)), fillColorArgb: \(String(describing: fillColorArgb)), strokeColorArgb: \(String(describing: strokeColorArgb)), lineWidth: \(String(describing: lineWidth)), zIndex: \(String(describing: zIndex)), isHidden: \(String(describing: isHidden)), consumeTapEvents: \(String(describing: consumeTapEvents)), level: \(String(describing: level)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformTileOverlay: Hashable, CustomStringConvertible {
  var id: String
  var urlTemplate: String
  var minimumZ: Int64
  var maximumZ: Int64
  var tileSize: Int64
  var canReplaceMapContent: Bool
  var alpha: Double
  var level: PlatformOverlayLevel


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformTileOverlay? {
    let id = pigeonVar_list[0] as! String
    let urlTemplate = pigeonVar_list[1] as! String
    let minimumZ = pigeonVar_list[2] as! Int64
    let maximumZ = pigeonVar_list[3] as! Int64
    let tileSize = pigeonVar_list[4] as! Int64
    let canReplaceMapContent = pigeonVar_list[5] as! Bool
    let alpha = pigeonVar_list[6] as! Double
    let level = pigeonVar_list[7] as! PlatformOverlayLevel

    return PlatformTileOverlay(
      id: id,
      urlTemplate: urlTemplate,
      minimumZ: minimumZ,
      maximumZ: maximumZ,
      tileSize: tileSize,
      canReplaceMapContent: canReplaceMapContent,
      alpha: alpha,
      level: level
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      urlTemplate,
      minimumZ,
      maximumZ,
      tileSize,
      canReplaceMapContent,
      alpha,
      level,
    ]
  }
  static func == (lhs: PlatformTileOverlay, rhs: PlatformTileOverlay) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.urlTemplate, rhs.urlTemplate) && messagesPigeonInternal.deepEquals(lhs.minimumZ, rhs.minimumZ) && messagesPigeonInternal.deepEquals(lhs.maximumZ, rhs.maximumZ) && messagesPigeonInternal.deepEquals(lhs.tileSize, rhs.tileSize) && messagesPigeonInternal.deepEquals(lhs.canReplaceMapContent, rhs.canReplaceMapContent) && messagesPigeonInternal.deepEquals(lhs.alpha, rhs.alpha) && messagesPigeonInternal.deepEquals(lhs.level, rhs.level)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformTileOverlay")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: urlTemplate, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: minimumZ, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: maximumZ, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: tileSize, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: canReplaceMapContent, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: alpha, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: level, hasher: &hasher)
  }

  public var description: String {
    return "PlatformTileOverlay(id: \(String(describing: id)), urlTemplate: \(String(describing: urlTemplate)), minimumZ: \(String(describing: minimumZ)), maximumZ: \(String(describing: maximumZ)), tileSize: \(String(describing: tileSize)), canReplaceMapContent: \(String(describing: canReplaceMapContent)), alpha: \(String(describing: alpha)), level: \(String(describing: level)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPointOfInterestFilter: Hashable, CustomStringConvertible {
  var mode: PlatformPOIMode
  /// Only meaningful for [PlatformPOIMode.including] /
  /// [PlatformPOIMode.excluding].
  var categories: [PlatformPointOfInterestCategory]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPointOfInterestFilter? {
    let mode = pigeonVar_list[0] as! PlatformPOIMode
    let categories = pigeonVar_list[1] as! [PlatformPointOfInterestCategory]

    return PlatformPointOfInterestFilter(
      mode: mode,
      categories: categories
    )
  }
  func toList() -> [Any?] {
    return [
      mode,
      categories,
    ]
  }
  static func == (lhs: PlatformPointOfInterestFilter, rhs: PlatformPointOfInterestFilter) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.mode, rhs.mode) && messagesPigeonInternal.deepEquals(lhs.categories, rhs.categories)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformPointOfInterestFilter")
    messagesPigeonInternal.deepHash(value: mode, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: categories, hasher: &hasher)
  }

  public var description: String {
    return "PlatformPointOfInterestFilter(mode: \(String(describing: mode)), categories: \(String(describing: categories)))"
  }
}

/// Mirrors `MKMapView.CameraZoomRange` — distances in meters.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCameraZoomRange: Hashable, CustomStringConvertible {
  var minCenterCoordinateDistance: Double? = nil
  var maxCenterCoordinateDistance: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCameraZoomRange? {
    let minCenterCoordinateDistance: Double? = nilOrValue(pigeonVar_list[0])
    let maxCenterCoordinateDistance: Double? = nilOrValue(pigeonVar_list[1])

    return PlatformCameraZoomRange(
      minCenterCoordinateDistance: minCenterCoordinateDistance,
      maxCenterCoordinateDistance: maxCenterCoordinateDistance
    )
  }
  func toList() -> [Any?] {
    return [
      minCenterCoordinateDistance,
      maxCenterCoordinateDistance,
    ]
  }
  static func == (lhs: PlatformCameraZoomRange, rhs: PlatformCameraZoomRange) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.minCenterCoordinateDistance, rhs.minCenterCoordinateDistance) && messagesPigeonInternal.deepEquals(lhs.maxCenterCoordinateDistance, rhs.maxCenterCoordinateDistance)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformCameraZoomRange")
    messagesPigeonInternal.deepHash(value: minCenterCoordinateDistance, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: maxCenterCoordinateDistance, hasher: &hasher)
  }

  public var description: String {
    return "PlatformCameraZoomRange(minCenterCoordinateDistance: \(String(describing: minCenterCoordinateDistance)), maxCenterCoordinateDistance: \(String(describing: maxCenterCoordinateDistance)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMapConfiguration: Hashable, CustomStringConvertible {
  var kind: PlatformMapKind
  var emphasisStyle: PlatformMapEmphasisStyle
  var elevationStyle: PlatformMapElevationStyle
  var showsTraffic: Bool
  var showsCompass: Bool
  var showsScale: Bool
  var showsUserLocation: Bool
  var showsUserTrackingButton: Bool
  var userTrackingMode: PlatformUserTrackingMode
  var insetsLayoutMarginsFromSafeArea: Bool
  var isRotateEnabled: Bool
  var isScrollEnabled: Bool
  var isZoomEnabled: Bool
  var isPitchEnabled: Bool
  var selectableMapFeatures: [PlatformMapFeatureOptions]
  var pointOfInterestFilter: PlatformPointOfInterestFilter? = nil
  var cameraZoomRange: PlatformCameraZoomRange? = nil
  var cameraBoundary: PlatformCoordinateRegion? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMapConfiguration? {
    let kind = pigeonVar_list[0] as! PlatformMapKind
    let emphasisStyle = pigeonVar_list[1] as! PlatformMapEmphasisStyle
    let elevationStyle = pigeonVar_list[2] as! PlatformMapElevationStyle
    let showsTraffic = pigeonVar_list[3] as! Bool
    let showsCompass = pigeonVar_list[4] as! Bool
    let showsScale = pigeonVar_list[5] as! Bool
    let showsUserLocation = pigeonVar_list[6] as! Bool
    let showsUserTrackingButton = pigeonVar_list[7] as! Bool
    let userTrackingMode = pigeonVar_list[8] as! PlatformUserTrackingMode
    let insetsLayoutMarginsFromSafeArea = pigeonVar_list[9] as! Bool
    let isRotateEnabled = pigeonVar_list[10] as! Bool
    let isScrollEnabled = pigeonVar_list[11] as! Bool
    let isZoomEnabled = pigeonVar_list[12] as! Bool
    let isPitchEnabled = pigeonVar_list[13] as! Bool
    let selectableMapFeatures = pigeonVar_list[14] as! [PlatformMapFeatureOptions]
    let pointOfInterestFilter: PlatformPointOfInterestFilter? = nilOrValue(pigeonVar_list[15])
    let cameraZoomRange: PlatformCameraZoomRange? = nilOrValue(pigeonVar_list[16])
    let cameraBoundary: PlatformCoordinateRegion? = nilOrValue(pigeonVar_list[17])

    return PlatformMapConfiguration(
      kind: kind,
      emphasisStyle: emphasisStyle,
      elevationStyle: elevationStyle,
      showsTraffic: showsTraffic,
      showsCompass: showsCompass,
      showsScale: showsScale,
      showsUserLocation: showsUserLocation,
      showsUserTrackingButton: showsUserTrackingButton,
      userTrackingMode: userTrackingMode,
      insetsLayoutMarginsFromSafeArea: insetsLayoutMarginsFromSafeArea,
      isRotateEnabled: isRotateEnabled,
      isScrollEnabled: isScrollEnabled,
      isZoomEnabled: isZoomEnabled,
      isPitchEnabled: isPitchEnabled,
      selectableMapFeatures: selectableMapFeatures,
      pointOfInterestFilter: pointOfInterestFilter,
      cameraZoomRange: cameraZoomRange,
      cameraBoundary: cameraBoundary
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      emphasisStyle,
      elevationStyle,
      showsTraffic,
      showsCompass,
      showsScale,
      showsUserLocation,
      showsUserTrackingButton,
      userTrackingMode,
      insetsLayoutMarginsFromSafeArea,
      isRotateEnabled,
      isScrollEnabled,
      isZoomEnabled,
      isPitchEnabled,
      selectableMapFeatures,
      pointOfInterestFilter,
      cameraZoomRange,
      cameraBoundary,
    ]
  }
  static func == (lhs: PlatformMapConfiguration, rhs: PlatformMapConfiguration) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && messagesPigeonInternal.deepEquals(lhs.emphasisStyle, rhs.emphasisStyle) && messagesPigeonInternal.deepEquals(lhs.elevationStyle, rhs.elevationStyle) && messagesPigeonInternal.deepEquals(lhs.showsTraffic, rhs.showsTraffic) && messagesPigeonInternal.deepEquals(lhs.showsCompass, rhs.showsCompass) && messagesPigeonInternal.deepEquals(lhs.showsScale, rhs.showsScale) && messagesPigeonInternal.deepEquals(lhs.showsUserLocation, rhs.showsUserLocation) && messagesPigeonInternal.deepEquals(lhs.showsUserTrackingButton, rhs.showsUserTrackingButton) && messagesPigeonInternal.deepEquals(lhs.userTrackingMode, rhs.userTrackingMode) && messagesPigeonInternal.deepEquals(lhs.insetsLayoutMarginsFromSafeArea, rhs.insetsLayoutMarginsFromSafeArea) && messagesPigeonInternal.deepEquals(lhs.isRotateEnabled, rhs.isRotateEnabled) && messagesPigeonInternal.deepEquals(lhs.isScrollEnabled, rhs.isScrollEnabled) && messagesPigeonInternal.deepEquals(lhs.isZoomEnabled, rhs.isZoomEnabled) && messagesPigeonInternal.deepEquals(lhs.isPitchEnabled, rhs.isPitchEnabled) && messagesPigeonInternal.deepEquals(lhs.selectableMapFeatures, rhs.selectableMapFeatures) && messagesPigeonInternal.deepEquals(lhs.pointOfInterestFilter, rhs.pointOfInterestFilter) && messagesPigeonInternal.deepEquals(lhs.cameraZoomRange, rhs.cameraZoomRange) && messagesPigeonInternal.deepEquals(lhs.cameraBoundary, rhs.cameraBoundary)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformMapConfiguration")
    messagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: emphasisStyle, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: elevationStyle, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: showsTraffic, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: showsCompass, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: showsScale, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: showsUserLocation, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: showsUserTrackingButton, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: userTrackingMode, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: insetsLayoutMarginsFromSafeArea, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isRotateEnabled, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isScrollEnabled, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isZoomEnabled, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isPitchEnabled, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: selectableMapFeatures, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: pointOfInterestFilter, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: cameraZoomRange, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: cameraBoundary, hasher: &hasher)
  }

  public var description: String {
    return "PlatformMapConfiguration(kind: \(String(describing: kind)), emphasisStyle: \(String(describing: emphasisStyle)), elevationStyle: \(String(describing: elevationStyle)), showsTraffic: \(String(describing: showsTraffic)), showsCompass: \(String(describing: showsCompass)), showsScale: \(String(describing: showsScale)), showsUserLocation: \(String(describing: showsUserLocation)), showsUserTrackingButton: \(String(describing: showsUserTrackingButton)), userTrackingMode: \(String(describing: userTrackingMode)), insetsLayoutMarginsFromSafeArea: \(String(describing: insetsLayoutMarginsFromSafeArea)), isRotateEnabled: \(String(describing: isRotateEnabled)), isScrollEnabled: \(String(describing: isScrollEnabled)), isZoomEnabled: \(String(describing: isZoomEnabled)), isPitchEnabled: \(String(describing: isPitchEnabled)), selectableMapFeatures: \(String(describing: selectableMapFeatures)), pointOfInterestFilter: \(String(describing: pointOfInterestFilter)), cameraZoomRange: \(String(describing: cameraZoomRange)), cameraBoundary: \(String(describing: cameraBoundary)))"
  }
}

/// Mirrors `MKMapSnapshotter.Options` plus plugin-drawn annotation/overlay
/// toggles.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformSnapshotOptions: Hashable, CustomStringConvertible {
  var showsBuildings: Bool
  var showsPointsOfInterest: Bool
  var showsAnnotations: Bool
  var showsOverlays: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformSnapshotOptions? {
    let showsBuildings = pigeonVar_list[0] as! Bool
    let showsPointsOfInterest = pigeonVar_list[1] as! Bool
    let showsAnnotations = pigeonVar_list[2] as! Bool
    let showsOverlays = pigeonVar_list[3] as! Bool

    return PlatformSnapshotOptions(
      showsBuildings: showsBuildings,
      showsPointsOfInterest: showsPointsOfInterest,
      showsAnnotations: showsAnnotations,
      showsOverlays: showsOverlays
    )
  }
  func toList() -> [Any?] {
    return [
      showsBuildings,
      showsPointsOfInterest,
      showsAnnotations,
      showsOverlays,
    ]
  }
  static func == (lhs: PlatformSnapshotOptions, rhs: PlatformSnapshotOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.showsBuildings, rhs.showsBuildings) && messagesPigeonInternal.deepEquals(lhs.showsPointsOfInterest, rhs.showsPointsOfInterest) && messagesPigeonInternal.deepEquals(lhs.showsAnnotations, rhs.showsAnnotations) && messagesPigeonInternal.deepEquals(lhs.showsOverlays, rhs.showsOverlays)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformSnapshotOptions")
    messagesPigeonInternal.deepHash(value: showsBuildings, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: showsPointsOfInterest, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: showsAnnotations, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: showsOverlays, hasher: &hasher)
  }

  public var description: String {
    return "PlatformSnapshotOptions(showsBuildings: \(String(describing: showsBuildings)), showsPointsOfInterest: \(String(describing: showsPointsOfInterest)), showsAnnotations: \(String(describing: showsAnnotations)), showsOverlays: \(String(describing: showsOverlays)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMapViewCreationParams: Hashable, CustomStringConvertible {
  var initialCamera: PlatformMapCamera
  var configuration: PlatformMapConfiguration
  var annotations: [PlatformAnnotation]
  var polylines: [PlatformPolyline]
  var polygons: [PlatformPolygon]
  var circles: [PlatformCircle]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMapViewCreationParams? {
    let initialCamera = pigeonVar_list[0] as! PlatformMapCamera
    let configuration = pigeonVar_list[1] as! PlatformMapConfiguration
    let annotations = pigeonVar_list[2] as! [PlatformAnnotation]
    let polylines = pigeonVar_list[3] as! [PlatformPolyline]
    let polygons = pigeonVar_list[4] as! [PlatformPolygon]
    let circles = pigeonVar_list[5] as! [PlatformCircle]

    return PlatformMapViewCreationParams(
      initialCamera: initialCamera,
      configuration: configuration,
      annotations: annotations,
      polylines: polylines,
      polygons: polygons,
      circles: circles
    )
  }
  func toList() -> [Any?] {
    return [
      initialCamera,
      configuration,
      annotations,
      polylines,
      polygons,
      circles,
    ]
  }
  static func == (lhs: PlatformMapViewCreationParams, rhs: PlatformMapViewCreationParams) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.initialCamera, rhs.initialCamera) && messagesPigeonInternal.deepEquals(lhs.configuration, rhs.configuration) && messagesPigeonInternal.deepEquals(lhs.annotations, rhs.annotations) && messagesPigeonInternal.deepEquals(lhs.polylines, rhs.polylines) && messagesPigeonInternal.deepEquals(lhs.polygons, rhs.polygons) && messagesPigeonInternal.deepEquals(lhs.circles, rhs.circles)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformMapViewCreationParams")
    messagesPigeonInternal.deepHash(value: initialCamera, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: configuration, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: annotations, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: polylines, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: polygons, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: circles, hasher: &hasher)
  }

  public var description: String {
    return "PlatformMapViewCreationParams(initialCamera: \(String(describing: initialCamera)), configuration: \(String(describing: configuration)), annotations: \(String(describing: annotations)), polylines: \(String(describing: polylines)), polygons: \(String(describing: polygons)), circles: \(String(describing: circles)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMapKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMapEmphasisStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMapElevationStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformUserTrackingMode(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformLineCap(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformLineJoin(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformPOIMode(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformOverlayLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformPointOfInterestCategory(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMapFeatureOptions(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformAnnotationIconType(rawValue: enumResultAsInt)
      }
      return nil
    case 140:
      return PlatformCoordinate.fromList(self.readValue() as! [Any?])
    case 141:
      return PlatformCoordinateSpan.fromList(self.readValue() as! [Any?])
    case 142:
      return PlatformCoordinateRegion.fromList(self.readValue() as! [Any?])
    case 143:
      return PlatformMapCamera.fromList(self.readValue() as! [Any?])
    case 144:
      return PlatformPoint.fromList(self.readValue() as! [Any?])
    case 145:
      return PlatformAnnotationIcon.fromList(self.readValue() as! [Any?])
    case 146:
      return PlatformAnnotation.fromList(self.readValue() as! [Any?])
    case 147:
      return PlatformPolyline.fromList(self.readValue() as! [Any?])
    case 148:
      return PlatformPolygon.fromList(self.readValue() as! [Any?])
    case 149:
      return PlatformCircle.fromList(self.readValue() as! [Any?])
    case 150:
      return PlatformTileOverlay.fromList(self.readValue() as! [Any?])
    case 151:
      return PlatformPointOfInterestFilter.fromList(self.readValue() as! [Any?])
    case 152:
      return PlatformCameraZoomRange.fromList(self.readValue() as! [Any?])
    case 153:
      return PlatformMapConfiguration.fromList(self.readValue() as! [Any?])
    case 154:
      return PlatformSnapshotOptions.fromList(self.readValue() as! [Any?])
    case 155:
      return PlatformMapViewCreationParams.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformMapKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformMapEmphasisStyle {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformMapElevationStyle {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformUserTrackingMode {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformLineCap {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformLineJoin {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformPOIMode {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformOverlayLevel {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformPointOfInterestCategory {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformMapFeatureOptions {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformAnnotationIconType {
      super.writeByte(139)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformCoordinate {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCoordinateSpan {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCoordinateRegion {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMapCamera {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPoint {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAnnotationIcon {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAnnotation {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPolyline {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPolygon {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCircle {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformTileOverlay {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPointOfInterestFilter {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCameraZoomRange {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMapConfiguration {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformSnapshotOptions {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMapViewCreationParams {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Flutter -> host. One instance per platform view, keyed by the view id via
/// Pigeon's `messageChannelSuffix`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MapKitHostApi {
  /// Pushes the full initial state immediately after the platform view is
  /// created.
  func initialize(params: PlatformMapViewCreationParams) throws
  /// `MKMapView.setCamera(_:animated:)`.
  func setCamera(camera: PlatformMapCamera, animated: Bool) throws
  /// `MKMapView.setRegion(_:animated:)`.
  func setRegion(region: PlatformCoordinateRegion, animated: Bool) throws
  /// `MKMapView.setCenter(_:animated:)`.
  func setCenter(coordinate: PlatformCoordinate, animated: Bool) throws
  /// `MKMapView.camera`.
  func getCamera() throws -> PlatformMapCamera
  /// `MKMapView.region`.
  func getRegion() throws -> PlatformCoordinateRegion
  /// `MKMapView.convert(_:toPointTo:)`.
  func convertToPoint(coordinate: PlatformCoordinate) throws -> PlatformPoint?
  /// `MKMapView.convert(_:toCoordinateFrom:)`.
  func convertToCoordinate(point: PlatformPoint) throws -> PlatformCoordinate?
  func updateAnnotations(toAdd: [PlatformAnnotation], toChange: [PlatformAnnotation], idsToRemove: [String]) throws
  func updatePolylines(toAdd: [PlatformPolyline], toChange: [PlatformPolyline], idsToRemove: [String]) throws
  func updatePolygons(toAdd: [PlatformPolygon], toChange: [PlatformPolygon], idsToRemove: [String]) throws
  func updateCircles(toAdd: [PlatformCircle], toChange: [PlatformCircle], idsToRemove: [String]) throws
  func updateMapConfiguration(configuration: PlatformMapConfiguration) throws
  func showCallout(annotationId: String) throws
  func hideCallout(annotationId: String) throws
  func isCalloutShown(annotationId: String) throws -> Bool
  /// Throws: `snapshot-failed`.
  func takeSnapshot(options: PlatformSnapshotOptions, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  func openLookAround(coordinate: PlatformCoordinate, completion: @escaping (Result<Bool, Error>) -> Void)
  func addTileOverlay(overlay: PlatformTileOverlay) throws
  func removeTileOverlay(tileOverlayId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MapKitHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `MapKitHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MapKitHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Pushes the full initial state immediately after the platform view is
    /// created.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsArg = args[0] as! PlatformMapViewCreationParams
        do {
          try api.initialize(params: paramsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// `MKMapView.setCamera(_:animated:)`.
    let setCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.setCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cameraArg = args[0] as! PlatformMapCamera
        let animatedArg = args[1] as! Bool
        do {
          try api.setCamera(camera: cameraArg, animated: animatedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCameraChannel.setMessageHandler(nil)
    }
    /// `MKMapView.setRegion(_:animated:)`.
    let setRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.setRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let regionArg = args[0] as! PlatformCoordinateRegion
        let animatedArg = args[1] as! Bool
        do {
          try api.setRegion(region: regionArg, animated: animatedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRegionChannel.setMessageHandler(nil)
    }
    /// `MKMapView.setCenter(_:animated:)`.
    let setCenterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.setCenter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCenterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let coordinateArg = args[0] as! PlatformCoordinate
        let animatedArg = args[1] as! Bool
        do {
          try api.setCenter(coordinate: coordinateArg, animated: animatedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCenterChannel.setMessageHandler(nil)
    }
    /// `MKMapView.camera`.
    let getCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.getCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCameraChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCamera()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCameraChannel.setMessageHandler(nil)
    }
    /// `MKMapView.region`.
    let getRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.getRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRegionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getRegion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getRegionChannel.setMessageHandler(nil)
    }
    /// `MKMapView.convert(_:toPointTo:)`.
    let convertToPointChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.convertToPoint\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      convertToPointChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let coordinateArg = args[0] as! PlatformCoordinate
        do {
          let result = try api.convertToPoint(coordinate: coordinateArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      convertToPointChannel.setMessageHandler(nil)
    }
    /// `MKMapView.convert(_:toCoordinateFrom:)`.
    let convertToCoordinateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.convertToCoordinate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      convertToCoordinateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pointArg = args[0] as! PlatformPoint
        do {
          let result = try api.convertToCoordinate(point: pointArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      convertToCoordinateChannel.setMessageHandler(nil)
    }
    let updateAnnotationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updateAnnotations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAnnotationsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let toAddArg = args[0] as! [PlatformAnnotation]
        let toChangeArg = args[1] as! [PlatformAnnotation]
        let idsToRemoveArg = args[2] as! [String]
        do {
          try api.updateAnnotations(toAdd: toAddArg, toChange: toChangeArg, idsToRemove: idsToRemoveArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateAnnotationsChannel.setMessageHandler(nil)
    }
    let updatePolylinesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updatePolylines\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePolylinesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let toAddArg = args[0] as! [PlatformPolyline]
        let toChangeArg = args[1] as! [PlatformPolyline]
        let idsToRemoveArg = args[2] as! [String]
        do {
          try api.updatePolylines(toAdd: toAddArg, toChange: toChangeArg, idsToRemove: idsToRemoveArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updatePolylinesChannel.setMessageHandler(nil)
    }
    let updatePolygonsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updatePolygons\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePolygonsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let toAddArg = args[0] as! [PlatformPolygon]
        let toChangeArg = args[1] as! [PlatformPolygon]
        let idsToRemoveArg = args[2] as! [String]
        do {
          try api.updatePolygons(toAdd: toAddArg, toChange: toChangeArg, idsToRemove: idsToRemoveArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updatePolygonsChannel.setMessageHandler(nil)
    }
    let updateCirclesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updateCircles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateCirclesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let toAddArg = args[0] as! [PlatformCircle]
        let toChangeArg = args[1] as! [PlatformCircle]
        let idsToRemoveArg = args[2] as! [String]
        do {
          try api.updateCircles(toAdd: toAddArg, toChange: toChangeArg, idsToRemove: idsToRemoveArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateCirclesChannel.setMessageHandler(nil)
    }
    let updateMapConfigurationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updateMapConfiguration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateMapConfigurationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! PlatformMapConfiguration
        do {
          try api.updateMapConfiguration(configuration: configurationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateMapConfigurationChannel.setMessageHandler(nil)
    }
    let showCalloutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.showCallout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showCalloutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let annotationIdArg = args[0] as! String
        do {
          try api.showCallout(annotationId: annotationIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showCalloutChannel.setMessageHandler(nil)
    }
    let hideCalloutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.hideCallout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hideCalloutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let annotationIdArg = args[0] as! String
        do {
          try api.hideCallout(annotationId: annotationIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hideCalloutChannel.setMessageHandler(nil)
    }
    let isCalloutShownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.isCalloutShown\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isCalloutShownChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let annotationIdArg = args[0] as! String
        do {
          let result = try api.isCalloutShown(annotationId: annotationIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isCalloutShownChannel.setMessageHandler(nil)
    }
    /// Throws: `snapshot-failed`.
    let takeSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.takeSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takeSnapshotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! PlatformSnapshotOptions
        api.takeSnapshot(options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      takeSnapshotChannel.setMessageHandler(nil)
    }
    let openLookAroundChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.openLookAround\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openLookAroundChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let coordinateArg = args[0] as! PlatformCoordinate
        api.openLookAround(coordinate: coordinateArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openLookAroundChannel.setMessageHandler(nil)
    }
    let addTileOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.addTileOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addTileOverlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let overlayArg = args[0] as! PlatformTileOverlay
        do {
          try api.addTileOverlay(overlay: overlayArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addTileOverlayChannel.setMessageHandler(nil)
    }
    let removeTileOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.removeTileOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeTileOverlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tileOverlayIdArg = args[0] as! String
        do {
          try api.removeTileOverlay(tileOverlayId: tileOverlayIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeTileOverlayChannel.setMessageHandler(nil)
    }
  }
}

/// Host -> Flutter. One instance per platform view, keyed by view id.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MapKitFlutterApiProtocol {
  func onCameraMoveStarted(completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onCameraMove(camera cameraArg: PlatformMapCamera, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onCameraIdle(completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onAnnotationTap(annotationId annotationIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onAnnotationDragStart(annotationId annotationIdArg: String, coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onAnnotationDrag(annotationId annotationIdArg: String, coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onAnnotationDragEnd(annotationId annotationIdArg: String, coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onCalloutTap(annotationId annotationIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onPolylineTap(polylineId polylineIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onPolygonTap(polygonId polygonIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onCircleTap(circleId circleIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onMapTap(coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  func onMapLongPress(coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  /// `MKMapViewDelegate.mapViewDidFailLoadingMap(_:withError:)`.
  func onDidFailLoadingMap(error errorArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
  /// `MKMapViewDelegate.mapView(_:didFailToLocateUserWithError:)`.
  func onDidFailToLocateUser(error errorArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void)
}
class MapKitFlutterApi: MapKitFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onCameraMoveStarted(completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCameraMoveStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCameraMove(camera cameraArg: PlatformMapCamera, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCameraMove\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([cameraArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCameraIdle(completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCameraIdle\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAnnotationTap(annotationId annotationIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onAnnotationTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([annotationIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAnnotationDragStart(annotationId annotationIdArg: String, coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onAnnotationDragStart\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([annotationIdArg, coordinateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAnnotationDrag(annotationId annotationIdArg: String, coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onAnnotationDrag\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([annotationIdArg, coordinateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAnnotationDragEnd(annotationId annotationIdArg: String, coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onAnnotationDragEnd\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([annotationIdArg, coordinateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCalloutTap(annotationId annotationIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCalloutTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([annotationIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPolylineTap(polylineId polylineIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onPolylineTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([polylineIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPolygonTap(polygonId polygonIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onPolygonTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([polygonIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCircleTap(circleId circleIdArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCircleTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([circleIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onMapTap(coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onMapTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([coordinateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onMapLongPress(coordinate coordinateArg: PlatformCoordinate, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onMapLongPress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([coordinateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// `MKMapViewDelegate.mapViewDidFailLoadingMap(_:withError:)`.
  func onDidFailLoadingMap(error errorArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onDidFailLoadingMap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// `MKMapViewDelegate.mapView(_:didFailToLocateUserWithError:)`.
  func onDidFailToLocateUser(error errorArg: String, completion: @escaping (Result<Void, MapKitHostError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onDidFailToLocateUser\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MapKitHostError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
