// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum PlatformMapKind { standard, hybrid, imagery }

/// Label and feature emphasis on the standard map
/// (`MKStandardMapConfiguration.EmphasisStyle`).
///
/// `standard` maps to Apple's `.default` — `default` is a Dart reserved word.
/// See: https://developer.apple.com/documentation/mapkit/mkstandardmapconfiguration/emphasisstyle
enum PlatformMapEmphasisStyle { standard, muted }

/// Flat versus realistic 3-D terrain (`MKMapConfiguration.ElevationStyle`).
/// See: https://developer.apple.com/documentation/mapkit/mkmapconfiguration/elevationstyle
enum PlatformMapElevationStyle { flat, realistic }

/// How the map camera follows the user's location (`MKUserTrackingMode`).
/// See: https://developer.apple.com/documentation/mapkit/mkusertrackingmode
enum PlatformUserTrackingMode { none, follow, followWithHeading }

/// Stroke end-cap style for an `MKPolyline` (`CGLineCap`).
/// See: https://developer.apple.com/documentation/coregraphics/cglinecap
enum PlatformLineCap { butt, round, square }

/// Stroke join style between `MKPolyline` segments (`CGLineJoin`).
/// See: https://developer.apple.com/documentation/coregraphics/cglinejoin
enum PlatformLineJoin { miter, round, bevel }

enum PlatformPOIMode { none, all, including, excluding }

/// Vertical placement of an overlay relative to the base map's own labels and
/// roads (`MKOverlayLevel`).
/// See: https://developer.apple.com/documentation/mapkit/mkoverlaylevel
enum PlatformOverlayLevel {
  /// Drawn above roads but below map labels (POIs, place names). Default.
  aboveRoads,

  /// Drawn above everything, including labels.
  aboveLabels,
}

/// Mirrors `MKPointOfInterestCategory`.
/// See: https://developer.apple.com/documentation/mapkit/mkpointofinterestcategory
enum PlatformPointOfInterestCategory {
  airport,
  amusementPark,
  aquarium,
  atm,
  bakery,
  bank,
  beach,
  brewery,
  cafe,
  campground,
  carRental,
  evCharger,
  fireStation,
  fitnessCenter,
  foodMarket,
  gasStation,
  hospital,
  hotel,
  laundry,
  library,
  marina,
  movieTheater,
  museum,
  nationalPark,
  nightlife,
  park,
  parking,
  pharmacy,
  police,
  postOffice,
  publicTransport,
  restaurant,
  restroom,
  school,
  stadium,
  store,
  theater,
  university,
  winery,
  zoo,
}

/// Map features the user can select (`MKMapFeatureOptions`).
/// See: https://developer.apple.com/documentation/mapkit/mkmapfeatureoptions
enum PlatformMapFeatureOptions {
  pointsOfInterest,
  territories,
  physicalFeatures,
}

enum PlatformAnnotationIconType { marker, image }

class PlatformCoordinate {
  PlatformCoordinate({required this.latitude, required this.longitude});

  double latitude;

  double longitude;

  List<Object?> _toList() {
    return <Object?>[latitude, longitude];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCoordinate decode(Object result) {
    result as List<Object?>;
    return PlatformCoordinate(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCoordinate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) &&
        _deepEquals(longitude, other.longitude);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCoordinate(latitude: $latitude, longitude: $longitude)';
  }
}

class PlatformCoordinateSpan {
  PlatformCoordinateSpan({
    required this.latitudeDelta,
    required this.longitudeDelta,
  });

  double latitudeDelta;

  double longitudeDelta;

  List<Object?> _toList() {
    return <Object?>[latitudeDelta, longitudeDelta];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCoordinateSpan decode(Object result) {
    result as List<Object?>;
    return PlatformCoordinateSpan(
      latitudeDelta: result[0]! as double,
      longitudeDelta: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCoordinateSpan || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitudeDelta, other.latitudeDelta) &&
        _deepEquals(longitudeDelta, other.longitudeDelta);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCoordinateSpan(latitudeDelta: $latitudeDelta, longitudeDelta: $longitudeDelta)';
  }
}

class PlatformCoordinateRegion {
  PlatformCoordinateRegion({required this.center, required this.span});

  PlatformCoordinate center;

  PlatformCoordinateSpan span;

  List<Object?> _toList() {
    return <Object?>[center, span];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCoordinateRegion decode(Object result) {
    result as List<Object?>;
    return PlatformCoordinateRegion(
      center: result[0]! as PlatformCoordinate,
      span: result[1]! as PlatformCoordinateSpan,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCoordinateRegion ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(center, other.center) && _deepEquals(span, other.span);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCoordinateRegion(center: $center, span: $span)';
  }
}

/// Mirrors `MKMapCamera`: [distance] is `centerCoordinateDistance` in meters.
class PlatformMapCamera {
  PlatformMapCamera({
    required this.centerCoordinate,
    required this.distance,
    required this.heading,
    required this.pitch,
  });

  PlatformCoordinate centerCoordinate;

  double distance;

  double heading;

  double pitch;

  List<Object?> _toList() {
    return <Object?>[centerCoordinate, distance, heading, pitch];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMapCamera decode(Object result) {
    result as List<Object?>;
    return PlatformMapCamera(
      centerCoordinate: result[0]! as PlatformCoordinate,
      distance: result[1]! as double,
      heading: result[2]! as double,
      pitch: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMapCamera || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(centerCoordinate, other.centerCoordinate) &&
        _deepEquals(distance, other.distance) &&
        _deepEquals(heading, other.heading) &&
        _deepEquals(pitch, other.pitch);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformMapCamera(centerCoordinate: $centerCoordinate, distance: $distance, heading: $heading, pitch: $pitch)';
  }
}

class PlatformPoint {
  PlatformPoint({required this.x, required this.y});

  double x;

  double y;

  List<Object?> _toList() {
    return <Object?>[x, y];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPoint decode(Object result) {
    result as List<Object?>;
    return PlatformPoint(x: result[0]! as double, y: result[1]! as double);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPoint || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) && _deepEquals(y, other.y);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPoint(x: $x, y: $y)';
  }
}

/// Discriminated union of the `MKAnnotationIcon` variants. Only the fields
/// relevant to [type] are non-null.
class PlatformAnnotationIcon {
  PlatformAnnotationIcon({
    required this.type,
    this.markerTintArgb,
    this.glyphText,
    this.glyphSystemImage,
    this.glyphTintArgb,
    this.imageBytes,
  });

  PlatformAnnotationIconType type;

  /// `MKMarkerAnnotationView.markerTintColor` (ARGB) for the `marker` variant.
  int? markerTintArgb;

  /// `MKMarkerAnnotationView.glyphText` for the `marker` variant.
  String? glyphText;

  /// SF Symbol name for `MKMarkerAnnotationView.glyphImage`.
  String? glyphSystemImage;

  /// `MKMarkerAnnotationView.glyphTintColor` (ARGB).
  int? glyphTintArgb;

  /// Raw PNG bytes for the `image` variant (`MKAnnotationView.image`).
  Uint8List? imageBytes;

  List<Object?> _toList() {
    return <Object?>[
      type,
      markerTintArgb,
      glyphText,
      glyphSystemImage,
      glyphTintArgb,
      imageBytes,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformAnnotationIcon decode(Object result) {
    result as List<Object?>;
    return PlatformAnnotationIcon(
      type: result[0]! as PlatformAnnotationIconType,
      markerTintArgb: result[1] as int?,
      glyphText: result[2] as String?,
      glyphSystemImage: result[3] as String?,
      glyphTintArgb: result[4] as int?,
      imageBytes: result[5] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformAnnotationIcon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(markerTintArgb, other.markerTintArgb) &&
        _deepEquals(glyphText, other.glyphText) &&
        _deepEquals(glyphSystemImage, other.glyphSystemImage) &&
        _deepEquals(glyphTintArgb, other.glyphTintArgb) &&
        _deepEquals(imageBytes, other.imageBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformAnnotationIcon(type: $type, markerTintArgb: $markerTintArgb, glyphText: $glyphText, glyphSystemImage: $glyphSystemImage, glyphTintArgb: $glyphTintArgb, imageBytes: $imageBytes)';
  }
}

class PlatformAnnotation {
  PlatformAnnotation({
    required this.id,
    required this.coordinate,
    required this.icon,
    this.title,
    this.subtitle,
    required this.calloutConsumesTapEvents,
    required this.alpha,
    required this.anchorPointX,
    required this.anchorPointY,
    required this.isDraggable,
    required this.isHidden,
    required this.zPriority,
    this.clusteringIdentifier,
  });

  String id;

  PlatformCoordinate coordinate;

  PlatformAnnotationIcon icon;

  String? title;

  String? subtitle;

  bool calloutConsumesTapEvents;

  double alpha;

  double anchorPointX;

  double anchorPointY;

  bool isDraggable;

  bool isHidden;

  double zPriority;

  String? clusteringIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      id,
      coordinate,
      icon,
      title,
      subtitle,
      calloutConsumesTapEvents,
      alpha,
      anchorPointX,
      anchorPointY,
      isDraggable,
      isHidden,
      zPriority,
      clusteringIdentifier,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformAnnotation decode(Object result) {
    result as List<Object?>;
    return PlatformAnnotation(
      id: result[0]! as String,
      coordinate: result[1]! as PlatformCoordinate,
      icon: result[2]! as PlatformAnnotationIcon,
      title: result[3] as String?,
      subtitle: result[4] as String?,
      calloutConsumesTapEvents: result[5]! as bool,
      alpha: result[6]! as double,
      anchorPointX: result[7]! as double,
      anchorPointY: result[8]! as double,
      isDraggable: result[9]! as bool,
      isHidden: result[10]! as bool,
      zPriority: result[11]! as double,
      clusteringIdentifier: result[12] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformAnnotation || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(coordinate, other.coordinate) &&
        _deepEquals(icon, other.icon) &&
        _deepEquals(title, other.title) &&
        _deepEquals(subtitle, other.subtitle) &&
        _deepEquals(calloutConsumesTapEvents, other.calloutConsumesTapEvents) &&
        _deepEquals(alpha, other.alpha) &&
        _deepEquals(anchorPointX, other.anchorPointX) &&
        _deepEquals(anchorPointY, other.anchorPointY) &&
        _deepEquals(isDraggable, other.isDraggable) &&
        _deepEquals(isHidden, other.isHidden) &&
        _deepEquals(zPriority, other.zPriority) &&
        _deepEquals(clusteringIdentifier, other.clusteringIdentifier);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformAnnotation(id: $id, coordinate: $coordinate, icon: $icon, title: $title, subtitle: $subtitle, calloutConsumesTapEvents: $calloutConsumesTapEvents, alpha: $alpha, anchorPointX: $anchorPointX, anchorPointY: $anchorPointY, isDraggable: $isDraggable, isHidden: $isHidden, zPriority: $zPriority, clusteringIdentifier: $clusteringIdentifier)';
  }
}

class PlatformPolyline {
  PlatformPolyline({
    required this.id,
    required this.coordinates,
    required this.strokeColorArgb,
    required this.lineWidth,
    required this.lineCap,
    required this.lineJoin,
    required this.isHidden,
    required this.consumeTapEvents,
    required this.isGeodesic,
    required this.level,
    required this.zIndex,
    this.lineDashPattern,
    this.gradientColorsArgb,
  });

  String id;

  List<PlatformCoordinate> coordinates;

  int strokeColorArgb;

  double lineWidth;

  PlatformLineCap lineCap;

  PlatformLineJoin lineJoin;

  bool isHidden;

  bool consumeTapEvents;

  bool isGeodesic;

  PlatformOverlayLevel level;

  int zIndex;

  /// Alternating dash/gap lengths in points (`lineDashPattern`).
  List<double>? lineDashPattern;

  /// When non-empty, renders with `MKGradientPolylineRenderer` spreading these
  /// ARGB colors evenly across the line.
  List<int>? gradientColorsArgb;

  List<Object?> _toList() {
    return <Object?>[
      id,
      coordinates,
      strokeColorArgb,
      lineWidth,
      lineCap,
      lineJoin,
      isHidden,
      consumeTapEvents,
      isGeodesic,
      level,
      zIndex,
      lineDashPattern,
      gradientColorsArgb,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPolyline decode(Object result) {
    result as List<Object?>;
    return PlatformPolyline(
      id: result[0]! as String,
      coordinates: (result[1]! as List<Object?>).cast<PlatformCoordinate>(),
      strokeColorArgb: result[2]! as int,
      lineWidth: result[3]! as double,
      lineCap: result[4]! as PlatformLineCap,
      lineJoin: result[5]! as PlatformLineJoin,
      isHidden: result[6]! as bool,
      consumeTapEvents: result[7]! as bool,
      isGeodesic: result[8]! as bool,
      level: result[9]! as PlatformOverlayLevel,
      zIndex: result[10]! as int,
      lineDashPattern: (result[11] as List<Object?>?)?.cast<double>(),
      gradientColorsArgb: (result[12] as List<Object?>?)?.cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPolyline || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(coordinates, other.coordinates) &&
        _deepEquals(strokeColorArgb, other.strokeColorArgb) &&
        _deepEquals(lineWidth, other.lineWidth) &&
        _deepEquals(lineCap, other.lineCap) &&
        _deepEquals(lineJoin, other.lineJoin) &&
        _deepEquals(isHidden, other.isHidden) &&
        _deepEquals(consumeTapEvents, other.consumeTapEvents) &&
        _deepEquals(isGeodesic, other.isGeodesic) &&
        _deepEquals(level, other.level) &&
        _deepEquals(zIndex, other.zIndex) &&
        _deepEquals(lineDashPattern, other.lineDashPattern) &&
        _deepEquals(gradientColorsArgb, other.gradientColorsArgb);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPolyline(id: $id, coordinates: $coordinates, strokeColorArgb: $strokeColorArgb, lineWidth: $lineWidth, lineCap: $lineCap, lineJoin: $lineJoin, isHidden: $isHidden, consumeTapEvents: $consumeTapEvents, isGeodesic: $isGeodesic, level: $level, zIndex: $zIndex, lineDashPattern: $lineDashPattern, gradientColorsArgb: $gradientColorsArgb)';
  }
}

class PlatformPolygon {
  PlatformPolygon({
    required this.id,
    required this.coordinates,
    required this.interiorPolygons,
    required this.fillColorArgb,
    required this.strokeColorArgb,
    required this.lineWidth,
    required this.zIndex,
    required this.isHidden,
    required this.consumeTapEvents,
    required this.level,
  });

  String id;

  List<PlatformCoordinate> coordinates;

  List<List<PlatformCoordinate>> interiorPolygons;

  int fillColorArgb;

  int strokeColorArgb;

  double lineWidth;

  int zIndex;

  bool isHidden;

  bool consumeTapEvents;

  PlatformOverlayLevel level;

  List<Object?> _toList() {
    return <Object?>[
      id,
      coordinates,
      interiorPolygons,
      fillColorArgb,
      strokeColorArgb,
      lineWidth,
      zIndex,
      isHidden,
      consumeTapEvents,
      level,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPolygon decode(Object result) {
    result as List<Object?>;
    return PlatformPolygon(
      id: result[0]! as String,
      coordinates: (result[1]! as List<Object?>).cast<PlatformCoordinate>(),
      interiorPolygons: (result[2]! as List<Object?>)
          .cast<List<PlatformCoordinate>>(),
      fillColorArgb: result[3]! as int,
      strokeColorArgb: result[4]! as int,
      lineWidth: result[5]! as double,
      zIndex: result[6]! as int,
      isHidden: result[7]! as bool,
      consumeTapEvents: result[8]! as bool,
      level: result[9]! as PlatformOverlayLevel,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPolygon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(coordinates, other.coordinates) &&
        _deepEquals(interiorPolygons, other.interiorPolygons) &&
        _deepEquals(fillColorArgb, other.fillColorArgb) &&
        _deepEquals(strokeColorArgb, other.strokeColorArgb) &&
        _deepEquals(lineWidth, other.lineWidth) &&
        _deepEquals(zIndex, other.zIndex) &&
        _deepEquals(isHidden, other.isHidden) &&
        _deepEquals(consumeTapEvents, other.consumeTapEvents) &&
        _deepEquals(level, other.level);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPolygon(id: $id, coordinates: $coordinates, interiorPolygons: $interiorPolygons, fillColorArgb: $fillColorArgb, strokeColorArgb: $strokeColorArgb, lineWidth: $lineWidth, zIndex: $zIndex, isHidden: $isHidden, consumeTapEvents: $consumeTapEvents, level: $level)';
  }
}

class PlatformCircle {
  PlatformCircle({
    required this.id,
    required this.center,
    required this.radius,
    required this.fillColorArgb,
    required this.strokeColorArgb,
    required this.lineWidth,
    required this.zIndex,
    required this.isHidden,
    required this.consumeTapEvents,
    required this.level,
  });

  String id;

  PlatformCoordinate center;

  double radius;

  int fillColorArgb;

  int strokeColorArgb;

  double lineWidth;

  int zIndex;

  bool isHidden;

  bool consumeTapEvents;

  PlatformOverlayLevel level;

  List<Object?> _toList() {
    return <Object?>[
      id,
      center,
      radius,
      fillColorArgb,
      strokeColorArgb,
      lineWidth,
      zIndex,
      isHidden,
      consumeTapEvents,
      level,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCircle decode(Object result) {
    result as List<Object?>;
    return PlatformCircle(
      id: result[0]! as String,
      center: result[1]! as PlatformCoordinate,
      radius: result[2]! as double,
      fillColorArgb: result[3]! as int,
      strokeColorArgb: result[4]! as int,
      lineWidth: result[5]! as double,
      zIndex: result[6]! as int,
      isHidden: result[7]! as bool,
      consumeTapEvents: result[8]! as bool,
      level: result[9]! as PlatformOverlayLevel,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCircle || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(center, other.center) &&
        _deepEquals(radius, other.radius) &&
        _deepEquals(fillColorArgb, other.fillColorArgb) &&
        _deepEquals(strokeColorArgb, other.strokeColorArgb) &&
        _deepEquals(lineWidth, other.lineWidth) &&
        _deepEquals(zIndex, other.zIndex) &&
        _deepEquals(isHidden, other.isHidden) &&
        _deepEquals(consumeTapEvents, other.consumeTapEvents) &&
        _deepEquals(level, other.level);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCircle(id: $id, center: $center, radius: $radius, fillColorArgb: $fillColorArgb, strokeColorArgb: $strokeColorArgb, lineWidth: $lineWidth, zIndex: $zIndex, isHidden: $isHidden, consumeTapEvents: $consumeTapEvents, level: $level)';
  }
}

class PlatformTileOverlay {
  PlatformTileOverlay({
    required this.id,
    required this.urlTemplate,
    required this.minimumZ,
    required this.maximumZ,
    required this.tileSize,
    required this.canReplaceMapContent,
    required this.alpha,
    required this.level,
  });

  String id;

  String urlTemplate;

  int minimumZ;

  int maximumZ;

  int tileSize;

  bool canReplaceMapContent;

  double alpha;

  PlatformOverlayLevel level;

  List<Object?> _toList() {
    return <Object?>[
      id,
      urlTemplate,
      minimumZ,
      maximumZ,
      tileSize,
      canReplaceMapContent,
      alpha,
      level,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformTileOverlay decode(Object result) {
    result as List<Object?>;
    return PlatformTileOverlay(
      id: result[0]! as String,
      urlTemplate: result[1]! as String,
      minimumZ: result[2]! as int,
      maximumZ: result[3]! as int,
      tileSize: result[4]! as int,
      canReplaceMapContent: result[5]! as bool,
      alpha: result[6]! as double,
      level: result[7]! as PlatformOverlayLevel,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformTileOverlay || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(urlTemplate, other.urlTemplate) &&
        _deepEquals(minimumZ, other.minimumZ) &&
        _deepEquals(maximumZ, other.maximumZ) &&
        _deepEquals(tileSize, other.tileSize) &&
        _deepEquals(canReplaceMapContent, other.canReplaceMapContent) &&
        _deepEquals(alpha, other.alpha) &&
        _deepEquals(level, other.level);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformTileOverlay(id: $id, urlTemplate: $urlTemplate, minimumZ: $minimumZ, maximumZ: $maximumZ, tileSize: $tileSize, canReplaceMapContent: $canReplaceMapContent, alpha: $alpha, level: $level)';
  }
}

class PlatformPointOfInterestFilter {
  PlatformPointOfInterestFilter({required this.mode, required this.categories});

  PlatformPOIMode mode;

  /// Only meaningful for [PlatformPOIMode.including] /
  /// [PlatformPOIMode.excluding].
  List<PlatformPointOfInterestCategory> categories;

  List<Object?> _toList() {
    return <Object?>[mode, categories];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPointOfInterestFilter decode(Object result) {
    result as List<Object?>;
    return PlatformPointOfInterestFilter(
      mode: result[0]! as PlatformPOIMode,
      categories: (result[1]! as List<Object?>)
          .cast<PlatformPointOfInterestCategory>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPointOfInterestFilter ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mode, other.mode) &&
        _deepEquals(categories, other.categories);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPointOfInterestFilter(mode: $mode, categories: $categories)';
  }
}

/// Mirrors `MKMapView.CameraZoomRange` — distances in meters.
class PlatformCameraZoomRange {
  PlatformCameraZoomRange({
    this.minCenterCoordinateDistance,
    this.maxCenterCoordinateDistance,
  });

  double? minCenterCoordinateDistance;

  double? maxCenterCoordinateDistance;

  List<Object?> _toList() {
    return <Object?>[minCenterCoordinateDistance, maxCenterCoordinateDistance];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraZoomRange decode(Object result) {
    result as List<Object?>;
    return PlatformCameraZoomRange(
      minCenterCoordinateDistance: result[0] as double?,
      maxCenterCoordinateDistance: result[1] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraZoomRange || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(
          minCenterCoordinateDistance,
          other.minCenterCoordinateDistance,
        ) &&
        _deepEquals(
          maxCenterCoordinateDistance,
          other.maxCenterCoordinateDistance,
        );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCameraZoomRange(minCenterCoordinateDistance: $minCenterCoordinateDistance, maxCenterCoordinateDistance: $maxCenterCoordinateDistance)';
  }
}

class PlatformMapConfiguration {
  PlatformMapConfiguration({
    required this.kind,
    required this.emphasisStyle,
    required this.elevationStyle,
    required this.showsTraffic,
    required this.showsCompass,
    required this.showsScale,
    required this.showsUserLocation,
    required this.showsUserTrackingButton,
    required this.userTrackingMode,
    required this.insetsLayoutMarginsFromSafeArea,
    required this.isRotateEnabled,
    required this.isScrollEnabled,
    required this.isZoomEnabled,
    required this.isPitchEnabled,
    required this.selectableMapFeatures,
    this.pointOfInterestFilter,
    this.cameraZoomRange,
    this.cameraBoundary,
  });

  PlatformMapKind kind;

  PlatformMapEmphasisStyle emphasisStyle;

  PlatformMapElevationStyle elevationStyle;

  bool showsTraffic;

  bool showsCompass;

  bool showsScale;

  bool showsUserLocation;

  bool showsUserTrackingButton;

  PlatformUserTrackingMode userTrackingMode;

  bool insetsLayoutMarginsFromSafeArea;

  bool isRotateEnabled;

  bool isScrollEnabled;

  bool isZoomEnabled;

  bool isPitchEnabled;

  List<PlatformMapFeatureOptions> selectableMapFeatures;

  PlatformPointOfInterestFilter? pointOfInterestFilter;

  PlatformCameraZoomRange? cameraZoomRange;

  PlatformCoordinateRegion? cameraBoundary;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      emphasisStyle,
      elevationStyle,
      showsTraffic,
      showsCompass,
      showsScale,
      showsUserLocation,
      showsUserTrackingButton,
      userTrackingMode,
      insetsLayoutMarginsFromSafeArea,
      isRotateEnabled,
      isScrollEnabled,
      isZoomEnabled,
      isPitchEnabled,
      selectableMapFeatures,
      pointOfInterestFilter,
      cameraZoomRange,
      cameraBoundary,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMapConfiguration decode(Object result) {
    result as List<Object?>;
    return PlatformMapConfiguration(
      kind: result[0]! as PlatformMapKind,
      emphasisStyle: result[1]! as PlatformMapEmphasisStyle,
      elevationStyle: result[2]! as PlatformMapElevationStyle,
      showsTraffic: result[3]! as bool,
      showsCompass: result[4]! as bool,
      showsScale: result[5]! as bool,
      showsUserLocation: result[6]! as bool,
      showsUserTrackingButton: result[7]! as bool,
      userTrackingMode: result[8]! as PlatformUserTrackingMode,
      insetsLayoutMarginsFromSafeArea: result[9]! as bool,
      isRotateEnabled: result[10]! as bool,
      isScrollEnabled: result[11]! as bool,
      isZoomEnabled: result[12]! as bool,
      isPitchEnabled: result[13]! as bool,
      selectableMapFeatures: (result[14]! as List<Object?>)
          .cast<PlatformMapFeatureOptions>(),
      pointOfInterestFilter: result[15] as PlatformPointOfInterestFilter?,
      cameraZoomRange: result[16] as PlatformCameraZoomRange?,
      cameraBoundary: result[17] as PlatformCoordinateRegion?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMapConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(emphasisStyle, other.emphasisStyle) &&
        _deepEquals(elevationStyle, other.elevationStyle) &&
        _deepEquals(showsTraffic, other.showsTraffic) &&
        _deepEquals(showsCompass, other.showsCompass) &&
        _deepEquals(showsScale, other.showsScale) &&
        _deepEquals(showsUserLocation, other.showsUserLocation) &&
        _deepEquals(showsUserTrackingButton, other.showsUserTrackingButton) &&
        _deepEquals(userTrackingMode, other.userTrackingMode) &&
        _deepEquals(
          insetsLayoutMarginsFromSafeArea,
          other.insetsLayoutMarginsFromSafeArea,
        ) &&
        _deepEquals(isRotateEnabled, other.isRotateEnabled) &&
        _deepEquals(isScrollEnabled, other.isScrollEnabled) &&
        _deepEquals(isZoomEnabled, other.isZoomEnabled) &&
        _deepEquals(isPitchEnabled, other.isPitchEnabled) &&
        _deepEquals(selectableMapFeatures, other.selectableMapFeatures) &&
        _deepEquals(pointOfInterestFilter, other.pointOfInterestFilter) &&
        _deepEquals(cameraZoomRange, other.cameraZoomRange) &&
        _deepEquals(cameraBoundary, other.cameraBoundary);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformMapConfiguration(kind: $kind, emphasisStyle: $emphasisStyle, elevationStyle: $elevationStyle, showsTraffic: $showsTraffic, showsCompass: $showsCompass, showsScale: $showsScale, showsUserLocation: $showsUserLocation, showsUserTrackingButton: $showsUserTrackingButton, userTrackingMode: $userTrackingMode, insetsLayoutMarginsFromSafeArea: $insetsLayoutMarginsFromSafeArea, isRotateEnabled: $isRotateEnabled, isScrollEnabled: $isScrollEnabled, isZoomEnabled: $isZoomEnabled, isPitchEnabled: $isPitchEnabled, selectableMapFeatures: $selectableMapFeatures, pointOfInterestFilter: $pointOfInterestFilter, cameraZoomRange: $cameraZoomRange, cameraBoundary: $cameraBoundary)';
  }
}

/// Mirrors `MKMapSnapshotter.Options` plus plugin-drawn annotation/overlay
/// toggles.
class PlatformSnapshotOptions {
  PlatformSnapshotOptions({
    required this.showsBuildings,
    required this.showsPointsOfInterest,
    required this.showsAnnotations,
    required this.showsOverlays,
  });

  bool showsBuildings;

  bool showsPointsOfInterest;

  bool showsAnnotations;

  bool showsOverlays;

  List<Object?> _toList() {
    return <Object?>[
      showsBuildings,
      showsPointsOfInterest,
      showsAnnotations,
      showsOverlays,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformSnapshotOptions decode(Object result) {
    result as List<Object?>;
    return PlatformSnapshotOptions(
      showsBuildings: result[0]! as bool,
      showsPointsOfInterest: result[1]! as bool,
      showsAnnotations: result[2]! as bool,
      showsOverlays: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformSnapshotOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(showsBuildings, other.showsBuildings) &&
        _deepEquals(showsPointsOfInterest, other.showsPointsOfInterest) &&
        _deepEquals(showsAnnotations, other.showsAnnotations) &&
        _deepEquals(showsOverlays, other.showsOverlays);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformSnapshotOptions(showsBuildings: $showsBuildings, showsPointsOfInterest: $showsPointsOfInterest, showsAnnotations: $showsAnnotations, showsOverlays: $showsOverlays)';
  }
}

class PlatformMapViewCreationParams {
  PlatformMapViewCreationParams({
    required this.initialCamera,
    required this.configuration,
    required this.annotations,
    required this.polylines,
    required this.polygons,
    required this.circles,
  });

  PlatformMapCamera initialCamera;

  PlatformMapConfiguration configuration;

  List<PlatformAnnotation> annotations;

  List<PlatformPolyline> polylines;

  List<PlatformPolygon> polygons;

  List<PlatformCircle> circles;

  List<Object?> _toList() {
    return <Object?>[
      initialCamera,
      configuration,
      annotations,
      polylines,
      polygons,
      circles,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMapViewCreationParams decode(Object result) {
    result as List<Object?>;
    return PlatformMapViewCreationParams(
      initialCamera: result[0]! as PlatformMapCamera,
      configuration: result[1]! as PlatformMapConfiguration,
      annotations: (result[2]! as List<Object?>).cast<PlatformAnnotation>(),
      polylines: (result[3]! as List<Object?>).cast<PlatformPolyline>(),
      polygons: (result[4]! as List<Object?>).cast<PlatformPolygon>(),
      circles: (result[5]! as List<Object?>).cast<PlatformCircle>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMapViewCreationParams ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(initialCamera, other.initialCamera) &&
        _deepEquals(configuration, other.configuration) &&
        _deepEquals(annotations, other.annotations) &&
        _deepEquals(polylines, other.polylines) &&
        _deepEquals(polygons, other.polygons) &&
        _deepEquals(circles, other.circles);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformMapViewCreationParams(initialCamera: $initialCamera, configuration: $configuration, annotations: $annotations, polylines: $polylines, polygons: $polygons, circles: $circles)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PlatformMapKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PlatformMapEmphasisStyle) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is PlatformMapElevationStyle) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PlatformUserTrackingMode) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is PlatformLineCap) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is PlatformLineJoin) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is PlatformPOIMode) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is PlatformOverlayLevel) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is PlatformPointOfInterestCategory) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is PlatformMapFeatureOptions) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    } else if (value is PlatformAnnotationIconType) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    } else if (value is PlatformCoordinate) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCoordinateSpan) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCoordinateRegion) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMapCamera) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPoint) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is PlatformAnnotationIcon) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is PlatformAnnotation) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPolyline) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPolygon) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCircle) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is PlatformTileOverlay) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPointOfInterestFilter) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCameraZoomRange) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMapConfiguration) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is PlatformSnapshotOptions) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMapViewCreationParams) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformMapKind.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformMapEmphasisStyle.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformMapElevationStyle.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformUserTrackingMode.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformLineCap.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformLineJoin.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformPOIMode.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformOverlayLevel.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : PlatformPointOfInterestCategory.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformMapFeatureOptions.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformAnnotationIconType.values[value];
      case 140:
        return PlatformCoordinate.decode(readValue(buffer)!);
      case 141:
        return PlatformCoordinateSpan.decode(readValue(buffer)!);
      case 142:
        return PlatformCoordinateRegion.decode(readValue(buffer)!);
      case 143:
        return PlatformMapCamera.decode(readValue(buffer)!);
      case 144:
        return PlatformPoint.decode(readValue(buffer)!);
      case 145:
        return PlatformAnnotationIcon.decode(readValue(buffer)!);
      case 146:
        return PlatformAnnotation.decode(readValue(buffer)!);
      case 147:
        return PlatformPolyline.decode(readValue(buffer)!);
      case 148:
        return PlatformPolygon.decode(readValue(buffer)!);
      case 149:
        return PlatformCircle.decode(readValue(buffer)!);
      case 150:
        return PlatformTileOverlay.decode(readValue(buffer)!);
      case 151:
        return PlatformPointOfInterestFilter.decode(readValue(buffer)!);
      case 152:
        return PlatformCameraZoomRange.decode(readValue(buffer)!);
      case 153:
        return PlatformMapConfiguration.decode(readValue(buffer)!);
      case 154:
        return PlatformSnapshotOptions.decode(readValue(buffer)!);
      case 155:
        return PlatformMapViewCreationParams.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter -> host. One instance per platform view, keyed by the view id via
/// Pigeon's `messageChannelSuffix`.
class MapKitHostApi {
  /// Constructor for [MapKitHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MapKitHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Pushes the full initial state immediately after the platform view is
  /// created.
  Future<void> initialize(PlatformMapViewCreationParams params) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[params],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// `MKMapView.setCamera(_:animated:)`.
  Future<void> setCamera(PlatformMapCamera camera, bool animated) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.setCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[camera, animated],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// `MKMapView.setRegion(_:animated:)`.
  Future<void> setRegion(PlatformCoordinateRegion region, bool animated) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.setRegion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[region, animated],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// `MKMapView.setCenter(_:animated:)`.
  Future<void> setCenter(PlatformCoordinate coordinate, bool animated) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.setCenter$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[coordinate, animated],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// `MKMapView.camera`.
  Future<PlatformMapCamera> getCamera() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.getCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PlatformMapCamera;
  }

  /// `MKMapView.region`.
  Future<PlatformCoordinateRegion> getRegion() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.getRegion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PlatformCoordinateRegion;
  }

  /// `MKMapView.convert(_:toPointTo:)`.
  Future<PlatformPoint?> convertToPoint(PlatformCoordinate coordinate) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.convertToPoint$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[coordinate],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as PlatformPoint?;
  }

  /// `MKMapView.convert(_:toCoordinateFrom:)`.
  Future<PlatformCoordinate?> convertToCoordinate(PlatformPoint point) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.convertToCoordinate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[point],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as PlatformCoordinate?;
  }

  Future<void> updateAnnotations(
    List<PlatformAnnotation> toAdd,
    List<PlatformAnnotation> toChange,
    List<String> idsToRemove,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updateAnnotations$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[toAdd, toChange, idsToRemove],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> updatePolylines(
    List<PlatformPolyline> toAdd,
    List<PlatformPolyline> toChange,
    List<String> idsToRemove,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updatePolylines$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[toAdd, toChange, idsToRemove],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> updatePolygons(
    List<PlatformPolygon> toAdd,
    List<PlatformPolygon> toChange,
    List<String> idsToRemove,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updatePolygons$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[toAdd, toChange, idsToRemove],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> updateCircles(
    List<PlatformCircle> toAdd,
    List<PlatformCircle> toChange,
    List<String> idsToRemove,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updateCircles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[toAdd, toChange, idsToRemove],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> updateMapConfiguration(
    PlatformMapConfiguration configuration,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.updateMapConfiguration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[configuration],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> showCallout(String annotationId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.showCallout$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[annotationId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> hideCallout(String annotationId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.hideCallout$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[annotationId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isCalloutShown(String annotationId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.isCalloutShown$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[annotationId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Throws: `snapshot-failed`.
  Future<Uint8List> takeSnapshot(PlatformSnapshotOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.takeSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[options],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<bool> openLookAround(PlatformCoordinate coordinate) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.openLookAround$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[coordinate],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> addTileOverlay(PlatformTileOverlay overlay) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.addTileOverlay$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[overlay],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> removeTileOverlay(String tileOverlayId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapkit_flutter.MapKitHostApi.removeTileOverlay$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[tileOverlayId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Host -> Flutter. One instance per platform view, keyed by view id.
abstract class MapKitFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onCameraMoveStarted();

  void onCameraMove(PlatformMapCamera camera);

  void onCameraIdle();

  void onAnnotationTap(String annotationId);

  void onAnnotationDragStart(
    String annotationId,
    PlatformCoordinate coordinate,
  );

  void onAnnotationDrag(String annotationId, PlatformCoordinate coordinate);

  void onAnnotationDragEnd(String annotationId, PlatformCoordinate coordinate);

  void onCalloutTap(String annotationId);

  void onPolylineTap(String polylineId);

  void onPolygonTap(String polygonId);

  void onCircleTap(String circleId);

  void onMapTap(PlatformCoordinate coordinate);

  void onMapLongPress(PlatformCoordinate coordinate);

  /// `MKMapViewDelegate.mapViewDidFailLoadingMap(_:withError:)`.
  void onDidFailLoadingMap(String error);

  /// `MKMapViewDelegate.mapView(_:didFailToLocateUserWithError:)`.
  void onDidFailToLocateUser(String error);

  static void setUp(
    MapKitFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCameraMoveStarted$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onCameraMoveStarted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCameraMove$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformMapCamera arg_camera = args[0]! as PlatformMapCamera;
          try {
            api.onCameraMove(arg_camera);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCameraIdle$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onCameraIdle();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onAnnotationTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_annotationId = args[0]! as String;
          try {
            api.onAnnotationTap(arg_annotationId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onAnnotationDragStart$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_annotationId = args[0]! as String;
          final PlatformCoordinate arg_coordinate =
              args[1]! as PlatformCoordinate;
          try {
            api.onAnnotationDragStart(arg_annotationId, arg_coordinate);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onAnnotationDrag$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_annotationId = args[0]! as String;
          final PlatformCoordinate arg_coordinate =
              args[1]! as PlatformCoordinate;
          try {
            api.onAnnotationDrag(arg_annotationId, arg_coordinate);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onAnnotationDragEnd$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_annotationId = args[0]! as String;
          final PlatformCoordinate arg_coordinate =
              args[1]! as PlatformCoordinate;
          try {
            api.onAnnotationDragEnd(arg_annotationId, arg_coordinate);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCalloutTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_annotationId = args[0]! as String;
          try {
            api.onCalloutTap(arg_annotationId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onPolylineTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_polylineId = args[0]! as String;
          try {
            api.onPolylineTap(arg_polylineId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onPolygonTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_polygonId = args[0]! as String;
          try {
            api.onPolygonTap(arg_polygonId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onCircleTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_circleId = args[0]! as String;
          try {
            api.onCircleTap(arg_circleId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onMapTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformCoordinate arg_coordinate =
              args[0]! as PlatformCoordinate;
          try {
            api.onMapTap(arg_coordinate);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onMapLongPress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformCoordinate arg_coordinate =
              args[0]! as PlatformCoordinate;
          try {
            api.onMapLongPress(arg_coordinate);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onDidFailLoadingMap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_error = args[0]! as String;
          try {
            api.onDidFailLoadingMap(arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapkit_flutter.MapKitFlutterApi.onDidFailToLocateUser$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_error = args[0]! as String;
          try {
            api.onDidFailToLocateUser(arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
